In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
raw_data = pd.read_csv("test_FD002.txt", sep = " ", header = None)

In [3]:
raw_data

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,1,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,...,8114.10,8.6476,0.03,369,2319,100.00,28.42,17.1551,NaN,NaN
1,1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,...,8053.06,9.2405,0.02,364,2324,100.00,24.29,14.8039,NaN,NaN
2,1,3,35.0045,0.8400,100.0,449.44,556.00,1359.08,1128.36,5.48,...,8053.04,9.3472,0.02,333,2223,100.00,14.98,8.9125,NaN,NaN
3,1,4,42.0066,0.8410,100.0,445.00,550.17,1349.69,1127.89,3.91,...,8066.90,9.3961,0.02,332,2212,100.00,10.35,6.4181,NaN,NaN
4,1,5,24.9985,0.6213,60.0,462.54,536.72,1253.18,1050.69,7.05,...,7865.66,10.8682,0.02,305,1915,84.93,14.31,8.5740,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33986,259,119,35.0015,0.8403,100.0,449.44,555.56,1366.01,1129.47,5.48,...,8088.36,9.3215,0.02,334,2223,100.00,14.94,8.9065,NaN,NaN
33987,259,120,42.0066,0.8405,100.0,445.00,549.42,1351.13,1123.86,3.91,...,8108.48,9.3542,0.02,332,2212,100.00,10.57,6.4075,NaN,NaN
33988,259,121,42.0061,0.8400,100.0,445.00,549.65,1349.14,1118.91,3.91,...,8098.77,9.3836,0.02,331,2212,100.00,10.57,6.4805,NaN,NaN
33989,259,122,0.0024,0.0003,100.0,518.67,642.58,1589.61,1408.16,14.62,...,8161.85,8.4279,0.03,393,2388,100.00,39.08,23.3589,NaN,NaN
33990,259,123,42.0033,0.8400,100.0,445.00,549.77,1342.50,1126.96,3.91,...,8105.28,9.3458,0.02,331,2212,100.00,10.63,6.3480,NaN,NaN

In [4]:
raw_data = raw_data.drop([26,27], axis='columns')

raw_data.columns = ['Engine_ID', 'Cycle', 'OpSet1', 'OpSet2', 'OpSet3', 'SensorMeasure1', 'SensorMeasure2', 'SensorMeasure3', 'SensorMeasure4', 'SensorMeasure5', 'SensorMeasure6', 'SensorMeasure7', 'SensorMeasure8', 'SensorMeasure9', 'SensorMeasure10', 'SensorMeasure11', 'SensorMeasure12', 'SensorMeasure13', 'SensorMeasure14', 'SensorMeasure15', 'SensorMeasure16', 'SensorMeasure17', 'SensorMeasure18', 'SensorMeasure19', 'SensorMeasure20', 'SensorMeasure21']
raw_data

,Engine_ID,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure1,SensorMeasure2,SensorMeasure3,SensorMeasure4,SensorMeasure5,...,SensorMeasure12,SensorMeasure13,SensorMeasure14,SensorMeasure15,SensorMeasure16,SensorMeasure17,SensorMeasure18,SensorMeasure19,SensorMeasure20,SensorMeasure21
0,1,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,...,371.69,2388.18,8114.10,8.6476,0.03,369,2319,100.00,28.42,17.1551
1,1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,...,315.32,2388.12,8053.06,9.2405,0.02,364,2324,100.00,24.29,14.8039
2,1,3,35.0045,0.8400,100.0,449.44,556.00,1359.08,1128.36,5.48,...,183.04,2387.75,8053.04,9.3472,0.02,333,2223,100.00,14.98,8.9125
3,1,4,42.0066,0.8410,100.0,445.00,550.17,1349.69,1127.89,3.91,...,130.40,2387.72,8066.90,9.3961,0.02,332,2212,100.00,10.35,6.4181
4,1,5,24.9985,0.6213,60.0,462.54,536.72,1253.18,1050.69,7.05,...,164.56,2028.05,7865.66,10.8682,0.02,305,1915,84.93,14.31,8.5740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33986,259,119,35.0015,0.8403,100.0,449.44,555.56,1366.01,1129.47,5.48,...,183.05,2388.39,8088.36,9.3215,0.02,334,2223,100.00,14.94,8.9065
33987,259,120,42.0066,0.8405,100.0,445.00,549.42,1351.13,1123.86,3.91,...,130.74,2388.31,8108.48,9.3542,0.02,332,2212,100.00,10.57,6.4075
33988,259,121,42.0061,0.8400,100.0,445.00,549.65,1349.14,1118.91,3.91,...,130.96,2388.34,8098.77,9.3836,0.02,331,2212,100.00,10.57,6.4805
33989,259,122,0.0024,0.0003,100.0,518.67,642.58,1589.61,1408.16,14.62,...,522.25,2388.00,8161.85,8.4279,0.03,393,2388,100.00,39.08,23.3589
33990,259,123,42.0033,0.8400,100.0,445.00,549.77,1342.50,1126.96,3.91,...,130.93,2388.40,8105.28,9.3458,0.02,331,2212,100.00,10.63,6.3480

In [5]:
raw_data[raw_data['Engine_ID'] == 1]

,Engine_ID,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure1,SensorMeasure2,SensorMeasure3,SensorMeasure4,SensorMeasure5,...,SensorMeasure12,SensorMeasure13,SensorMeasure14,SensorMeasure15,SensorMeasure16,SensorMeasure17,SensorMeasure18,SensorMeasure19,SensorMeasure20,SensorMeasure21
0,1,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,...,371.69,2388.18,8114.10,8.6476,0.03,369,2319,100.00,28.42,17.1551
1,1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,...,315.32,2388.12,8053.06,9.2405,0.02,364,2324,100.00,24.29,14.8039
2,1,3,35.0045,0.8400,100.0,449.44,556.00,1359.08,1128.36,5.48,...,183.04,2387.75,8053.04,9.3472,0.02,333,2223,100.00,14.98,8.9125
3,1,4,42.0066,0.8410,100.0,445.00,550.17,1349.69,1127.89,3.91,...,130.40,2387.72,8066.90,9.3961,0.02,332,2212,100.00,10.35,6.4181
4,1,5,24.9985,0.6213,60.0,462.54,536.72,1253.18,1050.69,7.05,...,164.56,2028.05,7865.66,10.8682,0.02,305,1915,84.93,14.31,8.5740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,1,254,42.0012,0.8413,100.0,445.00,550.08,1361.69,1144.96,3.91,...,131.03,2388.72,8123.94,9.4124,0.02,334,2212,100.00,10.47,6.3719
254,1,255,19.9995,0.7011,100.0,491.19,607.78,1494.91,1263.75,9.35,...,314.06,2388.50,8102.15,9.2726,0.03,368,2324,100.00,24.38,14.5958
255,1,256,25.0054,0.6200,60.0,462.54,537.52,1263.10,1053.32,7.05,...,164.29,2028.89,7907.38,10.9821,0.02,310,1915,84.93,14.24,8.5564
256,1,257,42.0048,0.8400,100.0,445.00,550.26,1355.02,1134.95,3.91,...,130.40,2388.65,8124.78,9.4040,0.02,333,2212,100.00,10.36,6.2911
257,1,258,10.0076,0.2501,100.0,489.05,605.42,1515.00,1325.07,10.52,...,370.87,2388.32,8167.06,8.7456,0.03,371,2319,100.00,28.30,17.0934

In [6]:
len(raw_data['Engine_ID'].unique())

259

In [8]:
cycle_ran_after = pd.read_csv('RUL_FD002.txt', sep=' ', header = None)
cycle_ran_after=cycle_ran_after.drop([1], axis='columns')
cycle_ran_after = np.array(cycle_ran_after)
cycle_ran_after

array([[ 18],
       [ 79],
       [106],
       [110],
       [ 15],
       [155],
       [  6],
       [ 90],
       [ 11],
       [ 79],
       [  6],
       [ 73],
       [ 30],
       [ 11],
       [ 37],
       [ 67],
       [ 68],
       [ 99],
       [ 22],
       [ 54],
       [ 97],
       [ 10],
       [142],
       [ 77],
       [ 88],
       [163],
       [126],
       [138],
       [ 83],
       [ 78],
       [ 75],
       [ 11],
       [ 53],
       [173],
       [ 63],
       [100],
       [151],
       [ 55],
       [ 48],
       [ 37],
       [ 44],
       [ 27],
       [ 18],
       [  6],
       [ 15],
       [112],
       [131],
       [ 13],
       [122],
       [ 13],
       [ 98],
       [ 53],
       [ 52],
       [106],
       [103],
       [152],
       [123],
       [ 26],
       [178],
       [ 73],
       [169],
       [ 39],
       [ 39],
       [ 14],
       [ 11],
       [121],
       [ 86],
       [ 56],
       [115],
       [ 17],
       [148],
       [104],
       [ 78],
       [ 86],
       [ 98],
       [ 36],
       [ 94],
       [ 52],
       [ 91],
       [ 15],
       [141],
       [ 74],
       [146],
       [ 17],
       [ 47],
       [194],
       [ 21],
       [ 79],
       [ 97],
       [  8],
       [  9],
       [ 73],
       [183],
       [ 97],
       [ 73],
       [ 49],
       [ 31],
       [ 97],
       [  9],
       [ 14],
       [106],
       [  8],
       [  8],
       [106],
       [116],
       [120],
       [ 61],
       [168],
       [ 35],
       [ 80],
       [  9],
       [ 50],
       [151],
       [ 78],
       [ 91],
       [  7],
       [181],
       [150],
       [106],
       [ 15],
       [ 67],
       [145],
       [180],
       [  7],
       [179],
       [124],
       [ 82],
       [108],
       [ 79],
       [121],
       [120],
       [ 39],
       [ 38],
       [  9],
       [167],
       [ 87],
       [ 88],
       [  7],
       [ 51],
       [ 55],
       [155],
       [ 47],
       [ 81],
       [ 43],
       [ 98],
       [ 10],
       [ 92],
       [ 11],
       [165],
       [ 34],
       [115],
       [ 59],
       [ 99],
       [103],
       [108],
       [ 83],
       [171],
       [ 15],
       [  9],
       [ 42],
       [ 13],
       [ 41],
       [ 88],
       [ 14],
       [155],
       [188],
       [ 96],
       [ 82],
       [135],
       [182],
       [ 36],
       [107],
       [ 14],
       [ 95],
       [142],
       [ 23],
       [  6],
       [144],
       [ 35],
       [ 97],
       [ 68],
       [ 14],
       [ 67],
       [191],
       [ 19],
       [ 10],
       [158],
       [183],
       [ 43],
       [ 12],
       [148],
       [ 13],
       [ 37],
       [122],
       [ 80],
       [ 93],
       [132],
       [ 32],
       [103],
       [174],
       [111],
       [ 68],
       [192],
       [121],
       [134],
       [ 48],
       [ 85],
       [  8],
       [ 23],
       [  8],
       [  6],
       [ 57],
       [ 83],
       [172],
       [101],
       [ 81],
       [ 86],
       [165],
       [ 73],
       [121],
       [139],
       [ 75],
       [151],
       [145],
       [ 11],
       [108],
       [ 14],
       [126],
       [ 61],
       [ 85],
       [  8],
       [101],
       [153],
       [ 89],
       [190],
       [ 12],
       [ 62],
       [134],
       [101],
       [121],
       [167],
       [ 17],
       [161],
       [181],
       [ 16],
       [152],
       [148],
       [ 56],
       [111],
       [ 23],
       [ 84],
       [ 12],
       [ 43],
       [ 48],
       [122],
       [191],
       [ 56],
       [131],
       [ 51]], dtype=int64)

In [9]:
given_no_of_cycles=[]
for i in range (1,len(raw_data['Engine_ID'].unique())+1):
    given_no_of_cycles.append(len(raw_data[raw_data['Engine_ID']==i]))
    print(len(raw_data[raw_data['Engine_ID']==i]))
    
given_no_of_cycles=np.array(given_no_of_cycles).reshape([cycle_ran_after.shape[0],1])

258
55
165
86
148
63
184
173
161
84
162
74
164
160
165
88
264
40
172
101
128
159
49
210
147
76
68
23
101
184
123
170
135
52
77
163
49
127
149
183
210
137
184
164
195
132
81
132
65
164
37
165
149
74
123
73
76
247
22
144
70
205
174
233
367
63
146
218
158
264
65
143
151
103
192
222
67
128
113
278
76
96
21
204
183
83
131
166
59
163
278
123
76
117
78
140
213
113
163
149
38
122
186
141
61
72
132
174
144
219
131
109
45
153
210
171
55
97
202
160
59
29
61
149
79
99
126
110
218
141
73
122
186
186
120
77
226
200
116
306
69
163
226
143
142
144
78
157
70
196
141
90
146
58
72
75
161
171
187
124
174
185
144
199
35
97
78
107
80
85
243
128
117
51
83
200
191
54
156
154
199
134
150
64
254
166
84
86
178
158
95
161
245
50
262
109
59
120
117
60
25
124
115
41
31
162
141
166
131
182
155
187
159
75
71
100
49
33
161
54
55
180
29
43
166
165
180
44
109
125
187
159
40
147
102
274
235
94
106
50
44
194
40
49
265
80
87
162
36
234
64
249
139
131
150
59
199
98
123

In [10]:
EOL=[]

i=0
for i in raw_data['Engine_ID']:
        EOL.append(given_no_of_cycles[i-1]+cycle_ran_after[i-1] )         
EOL = np.array(EOL).reshape([len(EOL),1])

In [11]:
EOL.shape

(33991, 1)

In [12]:
raw_data["EOL"] = EOL
raw_data.head(2)

,Engine_ID,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure1,SensorMeasure2,SensorMeasure3,SensorMeasure4,SensorMeasure5,...,SensorMeasure13,SensorMeasure14,SensorMeasure15,SensorMeasure16,SensorMeasure17,SensorMeasure18,SensorMeasure19,SensorMeasure20,SensorMeasure21,EOL
0,1,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,...,2388.18,8114.10,8.6476,0.03,369,2319,100.0,28.42,17.1551,276
1,1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,...,2388.12,8053.06,9.2405,0.02,364,2324,100.0,24.29,14.8039,276

In [13]:
raw_data["LR"] = raw_data["Cycle"].div(raw_data["EOL"])
# Drop ID and EOL
raw_data=raw_data.drop(columns=['Engine_ID','EOL'])
raw_data.head(2)

,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure1,SensorMeasure2,SensorMeasure3,SensorMeasure4,SensorMeasure5,SensorMeasure6,...,SensorMeasure13,SensorMeasure14,SensorMeasure15,SensorMeasure16,SensorMeasure17,SensorMeasure18,SensorMeasure19,SensorMeasure20,SensorMeasure21,LR
0,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,15.49,...,2388.18,8114.10,8.6476,0.03,369,2319,100.0,28.42,17.1551,0.003623
1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,13.66,...,2388.12,8053.06,9.2405,0.02,364,2324,100.0,24.29,14.8039,0.007246

In [14]:
labels=[]
for i in range (0,len(raw_data)):
    if np.array(raw_data["LR"])[i] <= 0.6:
        labels.append(0)
    elif np.array(raw_data["LR"])[i] <= 0.8 :
        labels.append(1)   
    else :
        labels.append(2)  
        
raw_data["labels"]=labels
raw_data  = raw_data.drop(columns=['LR'])   
raw_data

,Cycle,OpSet1,OpSet2,OpSet3,SensorMeasure1,SensorMeasure2,SensorMeasure3,SensorMeasure4,SensorMeasure5,SensorMeasure6,...,SensorMeasure13,SensorMeasure14,SensorMeasure15,SensorMeasure16,SensorMeasure17,SensorMeasure18,SensorMeasure19,SensorMeasure20,SensorMeasure21,labels
0,1,9.9987,0.2502,100.0,489.05,605.03,1497.17,1304.99,10.52,15.49,...,2388.18,8114.10,8.6476,0.03,369,2319,100.00,28.42,17.1551,0
1,2,20.0026,0.7000,100.0,491.19,607.82,1481.20,1246.11,9.35,13.66,...,2388.12,8053.06,9.2405,0.02,364,2324,100.00,24.29,14.8039,0
2,3,35.0045,0.8400,100.0,449.44,556.00,1359.08,1128.36,5.48,8.00,...,2387.75,8053.04,9.3472,0.02,333,2223,100.00,14.98,8.9125,0
3,4,42.0066,0.8410,100.0,445.00,550.17,1349.69,1127.89,3.91,5.71,...,2387.72,8066.90,9.3961,0.02,332,2212,100.00,10.35,6.4181,0
4,5,24.9985,0.6213,60.0,462.54,536.72,1253.18,1050.69,7.05,9.03,...,2028.05,7865.66,10.8682,0.02,305,1915,84.93,14.31,8.5740,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33986,119,35.0015,0.8403,100.0,449.44,555.56,1366.01,1129.47,5.48,8.00,...,2388.39,8088.36,9.3215,0.02,334,2223,100.00,14.94,8.9065,1
33987,120,42.0066,0.8405,100.0,445.00,549.42,1351.13,1123.86,3.91,5.72,...,2388.31,8108.48,9.3542,0.02,332,2212,100.00,10.57,6.4075,1
33988,121,42.0061,0.8400,100.0,445.00,549.65,1349.14,1118.91,3.91,5.72,...,2388.34,8098.77,9.3836,0.02,331,2212,100.00,10.57,6.4805,1
33989,122,0.0024,0.0003,100.0,518.67,642.58,1589.61,1408.16,14.62,21.61,...,2388.00,8161.85,8.4279,0.03,393,2388,100.00,39.08,23.3589,1
33990,123,42.0033,0.8400,100.0,445.00,549.77,1342.50,1126.96,3.91,5.71,...,2388.40,8105.28,9.3458,0.02,331,2212,100.00,10.63,6.3480,1

In [15]:
raw_data.to_csv("dtest2.csv", index = None)